from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from tbc_video_export.config.json import JsonConfig

DEFAULT_CONFIG: JsonConfig = {
    "profiles": [
        {
            "name": "ffv1",
            "default": True,
            "video_profile": "ffv1",
            "audio_profile": "flac",
            "filter_profiles": [],
        },
        {
            "name": "prores_hq",
            "video_profile": "prores_422_hq",
            "audio_profile": "pcm_24",
            "filter_profiles": [],
        },
        {
            "name": "prores_4444xq",
            "video_profile": "prores_4444_xq",
            "audio_profile": "pcm_24",
            "filter_profiles": [],
        },
        {
            "name": "v210",
            "video_profile": "v210",
            "audio_profile": "pcm_24",
            "filter_profiles": [],
        },
        {
            "name": "v410",
            "video_profile": "v410",
            "audio_profile": "pcm_24",
            "filter_profiles": [],
        },
        {
            "name": "d10",
            "video_profile": [
                "d10_mpeg2_pal",
                "d10_mpeg2_ntsc",
            ],
            "audio_profile": "pcm_24",
            "filter_profiles": [],
        },
        {
            "name": "x264",
            "video_profile": [
                "x264_web",
                "x264_lossless",
            ],
            "audio_profile": "aac",
            "filter_profiles": ["bwdif", "colorlevels32"],
        },
        {
            "name": "x265",
            "video_profile": [
                "x265_web",
                "x265_lossless",
            ],
            "audio_profile": "aac",
            "filter_profiles": ["bwdif", "colorlevels32"],
        },
        {
            "name": "av1",
            "video_profile": [
                "av1_web",
                "av1_lossless",
            ],
            "audio_profile": "aac",
            "filter_profiles": ["bwdif", "colorlevels32"],
        },
    ],
    "video_profiles": [
        {
            "name": "ffv1",
            "description": "FFV1",
            "codec": "ffv1",
            "video_format": "yuv422p10le",
            "container": "mkv",
            "opts": [
                "-coder",
                1,
                "-level",
                3,
                "-context",
                1,
                "-slices",
                24,
                "-slicecrc",
                1,
                "-g",
                1,
            ],
            "type": "lossless",
        },
        {
            "name": "prores_422_hq",
            "description": "ProRes 422 HQ",
            "codec": "prores",
            "video_format": "yuv422p10le",
            "container": "mov",
            "opts": [
                "-profile:v",
                "hq",
                "-vendor",
                "apl0",
                "-bits_per_mb",
                8000,
                "-quant_mat",
                "hq",
                "-mbs_per_slice",
                8,
            ],
        },
        {
            "name": "prores_4444_xq",
            "description": "ProRes 4444 XQ",
            "codec": "prores",
            "video_format": "yuv444p10le",
            "container": "mov",
            "opts": [
                "-profile:v",
                "xq",
                "-vendor",
                "apl0",
                "-bits_per_mb",
                8000,
                "-quant_mat",
                "hq",
                "-mbs_per_slice",
                8,
            ],
        },
        {
            "name": "v210",
            "description": "V210",
            "codec": "v210",
            "video_format": "yuv422p10le",
            "container": "mov",
            "type": "lossless",
        },
        {
            "name": "v410",
            "description": "V410",
            "codec": "v410",
            "video_format": "yuv422p10le",
            "container": "mov",
            "type": "lossless",
        },
        {
            "name": "d10_mpeg2_pal",
            "description": "D10 (Sony IMX/XDCAM)",
            "codec": "mpeg2video",
            "video_format": "yuv422p",
            "container": "mxf",
            "output_format": "mxf_d10",
            "opts": [
                "-minrate",
                "50000000",
                "-maxrate",
                "50000000",
                "-b:v",
                "50000000",
                "-g",
                1,
                "-flags",
                "ildct+ilme+low_delay",
                "-intra_vlc",
                1,
                "-non_linear_quant",
                1,
                "-dc",
                10,
                "-ps",
                1,
                "-qmin",
                1,
                "-qmax",
                3,
                "-bufsize",
                "2000000",
                "-rc_init_occupancy",
                "2000000",
            ],
            "video_system": "pal",
            "filter_profiles_additions": [
                "resize_pal_d10",
            ],
        },
        {
            "name": "d10_mpeg2_ntsc",
            "description": "D10 (Sony IMX/XDCAM) *BROKEN*",
            "codec": "mpeg2video",
            "video_format": "yuv422p",
            "container": "mxf",
            "output_format": "mxf_d10",
            "opts": [
                "-minrate",
                "49999840",
                "-maxrate",
                "49999840",
                "-b:v",
                "49999840",
                "-g",
                1,
                "-flags",
                "ildct+ilme+low_delay",
                "-intra_vlc",
                1,
                "-non_linear_quant",
                1,
                "-dc",
                10,
                "-ps",
                1,
                "-qmin",
                1,
                "-qmax",
                3,
                "-bufsize",
                "1668328",
                "-rc_init_occupancy",
                "1668328",
            ],
            "video_system": "ntsc",
            "filter_profiles_additions": [
                "resize_ntsc_d10",
            ],
        },
        {
            "name": "x264_web",
            "description": "H.264 AVC - Web",
            "codec": "libx264",
            "video_format": "yuv420p",
            "container": "mov",
            "opts": [
                "-crf",
                18,
                "-preset",
                "slow",
                "-maxrate",
                "8M",
                "-bufsize",
                "16M",
                "-movflags",
                "+faststart",
                "-x264opts",
                "interlaced=0",
            ],
        },
        {
            "name": "x264_lossless",
            "description": "H.264 AVC - Lossless",
            "codec": "libx264",
            "video_format": "yuv420p",
            "container": "mov",
            "opts": [
                "-qp",
                0,
                "-preset",
                "veryslow",
            ],
            "filter_profiles_override": [],
            "type": "lossless",
        },
        {
            "name": "x265_web",
            "description": "H.265 HEVC - Web",
            "codec": "libx265",
            "video_format": "yuv420p",
            "container": "mov",
            "opts": [
                "-crf",
                20,
                "-preset",
                "slow",
                "-maxrate",
                "8M",
                "-bufsize",
                "16M",
                "-movflags",
                "+faststart",
                "-x265-params",
                "interlace=false",
            ],
        },
        {
            "name": "x265_lossless",
            "description": "H.265 HEVC - Lossless",
            "codec": "libx265",
            "video_format": "yuv420p",
            "container": "mov",
            "opts": [
                "-preset",
                "veryslow",
                "-movflags",
                "+faststart",
                "-x265-params",
                "lossless=1",
            ],
            "filter_profiles_override": [],
            "type": "lossless",
        },
        {
            "name": "av1_web",
            "description": "AV1 - Web",
            "codec": "libaom-av1",
            "video_format": "yuv420p",
            "container": "mp4",
            "opts": [
                "-crf",
                30,
                "-cpu-used",
                6,
                "-row-mt",
                1,
                "-lag-in-frames",
                48,
                "-b:v",
                0,
                "-movflags",
                "+faststart",
            ],
        },
        {
            "name": "av1_lossless",
            "description": "AV1 - Lossless",
            "codec": "libaom-av1",
            "video_format": "yuv420p",
            "container": "mkv",
            "opts": [
                "-crf",
                0,
                "-cpu-used",
                6,
                "-row-mt",
                1,
                "-lag-in-frames",
                48,
                "-b:v",
                0,
                "-error-resilience",
                1,
                "-aom-params",
                "lossless=1",
            ],
            "filter_profiles_override": [],
            "type": "lossless",
        },
    ],
    "audio_profiles": [
        {
            "name": "flac",
            "description": "FLAC",
            "codec": "flac",
            "opts": ["-compression_level", 12],
        },
        {
            "name": "pcm_16",
            "description": "PCM 16-bits",
            "codec": "pcm_s16le",
        },
        {
            "name": "pcm_24",
            "description": "PCM 24-bits",
            "codec": "pcm_s24le",
        },
        {
            "name": "aac",
            "description": "AAC",
            "codec": "aac",
            "opts": ["-ar", 48000, "-b:a", "320K"],
        },
    ],
    "filter_profiles": [
        {
            "name": "bwdif",
            "description": "BWDIF",
            "video_filter": "bwdif",
        },
        {
            "name": "colorlevels32",
            "description": "Colorlevels (32)",
            "video_filter": "colorlevels=rimin=32/255:gimin=32/255:bimin=32/255",
        },
        {
            "name": "map_l_to_lr",
            "description": "Map L to L+R",
            "other_filter": "[2:a]pan=stereo|FL=FL|FR=FL",
        },
        {
            "name": "map_r_to_lr",
            "description": "Map R to L+R",
            "other_filter": "[2:a]pan=stereo|FR=FR|FL=FR",
        },
        {
            "name": "resize_pal_standard",
            "description": "Resize to PAL standard SD resoluton (720x576)",
            "video_filter": "scale=720x576:flags=lanczos,setdar=4/3",
        },
        {
            "name": "resize_ntsc_standard",
            "description": "Resize to NTSC standard SD resoluton (720x480)",
            "video_filter": "scale=720x480:flags=lanczos,setdar=4/3",
        },
        {
            "name": "resize_pal_d10",
            "description": "Resize and pad to D10 (Sony IMX/XDCAM) resoluton (720x608)",  # noqa: E501
            "video_filter": "scale=720x608:flags=lanczos",
        },
        {
            "name": "resize_ntsc_d10",
            "description": "Resize and pad to D10 (Sony IMX/XDCAM) resoluton (720x512)",  # noqa: E501
            "video_filter": "scale=720x512:flags=lanczos",
        },
    ],
}
