[project]
name = "tbc-video-export"
description = "Tool for exporting S-Video and CVBS-type TBCs to video files."
requires-python = ">=3.10"
readme = "README.md"
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
authors = [{ name = "Jitterbug", email = "jitterbug@posteo.co.uk" }]
dynamic = ["version"]

dependencies = [
    "typing-extensions (>=4.10.0,<5.0.0); python_version <= '3.10'",
    "pywin32 (>=306); sys_platform == 'win32'",
]

keywords = [
    "vhs-decode",
    "ld-decode",
    "cvbs-decode",
    "tbc",
    "rf capture",
]

classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: End Users/Desktop",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Multimedia :: Video",
    "Topic :: Multimedia :: Video :: Conversion",
]

[project.urls]
Homepage = "https://github.com/JuniorIsAJitterbug/tbc-video-export"
Issues = "https://github.com/JuniorIsAJitterbug/tbc-video-export/issues"
Documentation = "https://github.com/JuniorIsAJitterbug/tbc-video-export/wiki"
Discord = "https://discord.gg/pVVrrxd"

[project.scripts]
tbc-video-export = "tbc_video_export.__main__:main"

[build-system]
build-backend = "poetry_dynamic_versioning.backend"
requires = [
    "poetry-core>=1.0.0",
    "poetry-dynamic-versioning>=1.0.0,<2.0.0",
]

[dependency-groups]
dev = [
    "pytest (>=8.1.1,<10.0.0)",
    "pytest-mock (>=3.14.0,<4.0.0)",
    "pymediainfo (>=6.1.0,<8.0.0)",
]

build = [
    "dunamai (>=1.19.0,<2.0.0)",
    "python-appimage (>=1.0.0,<2.0.0); sys_platform == 'linux'",
    "pyinstaller (>=6.3.0,<7.0.0); python_version <= '3.14' and (sys_platform == 'win32' or sys_platform == 'darwin')",
    "pyinstaller-versionfile (>=2.1.1,<4.0.0); python_version <= '3.14' and sys_platform == 'win32'",
]

[tool.pyright]
include = ["src/**/*.py"]
exclude = ["tests/**/*.py"]
venvPath = ".venv"
typeCheckingMode = "strict"

[tool.ruff]
include = ["pyproject.toml", "src/**/*.py"]
extend-exclude = ["/nix/store"]
target-version = "py310"
select = [
    "PL",     # Pylint
    "I",      # isort
    "F",      # Pyflakes
    "D",      # pydocstyle
    "C90",    # mccabe
    "E",      # pycodestyle
    "W",      # pycodestyle
    "N",      # pep8-naming
    "UP",     # pyupgrade
    "SLF001", # private-member-access
    "TC",     # flake8-type-checking
    "ARG",    # flake8-unused-arguments
    "PTH",    # flake8-use-pathlib
    "A",      # flake8-builtins
    "C4",     # flake8-comprehensions
    "ISC",    # flake8-implicit-str-concat
    "G",      # flake8-logging-format
    "PIE",    # flake8-pie
    "B",      # flake8-bugbear
    "ICN",    # flake8-import-conventions
    "BLE",    # flake8-blind-except
    "TID",    # flake8-tidy-imports
    "RSE",    # flake8-raise
    "RET",    # flake8-return
    "SIM",    # flake8-simplify
    "PYI",    # flake8-pyi 
]

ignore = [
    "PLC0414", # useless-import-alias
    "PLR2004", # magic-value-comparison
    "PLC0415", # import-outside-top-level
    "PYI034",  # non-self-return-type
    "A005",    # stdlib-module-shadowing
    "D100",    # undocumented-public-module
    "D104",    # undocumented-public-package
    "D107",    # undocumented-public-init
    "G003",    # logging +
    "G004",    # logging f-string
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.isort]
required-imports = ["from __future__ import annotations"]

[tool.poetry]
version = "0.0.0"

[tool.poetry.requires-plugins]
poetry-dynamic-versioning = { version = ">=1.0.0,<2.0.0", extras = ["plugin"] }

[tool.poetry-dynamic-versioning]
enable = true
bump = true
vcs = "git"
style = "pep440"
metadata = false

[tool.poetry-dynamic-versioning.substitution]
files = ["tbc_video_export/common/consts.py"]
folders = [{ path = "src" }]
