blank_issues_enabled: false
contact_links:
  - name: 🙋 Ask a question on Discord! (or Reddit!) 
    url: https://discord.com/invite/pVVrrxd
    about: Check if your question has been answered on the [FAQ](https://github.com/JuniorIsAJitterbug/tbc-video-export/wiki/FAQ-Frequently-Asked-Questions) or create a new question.
