name: "Build and Release AppImage"

on:
  workflow_run:
    workflows: [PyPI]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  appimage:
    name: appimage
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }} && startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: cachix/install-nix-action@v25

      - name: Install
        run: nix develop --impure --accept-flake-config --command poetry install --with=appimage

      - name: Build AppImage
        run: nix develop --impure --accept-flake-config --command poetry run python-appimage build app -p 3.10 appimage/

      - name: Rename AppImage file
        run: mv tbc-video-export-x86_64.AppImage tbc-video-export.AppImage

      # AppImages require libfuse to run
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: fuse
          version: 1.0

      - name: Test AppImage
        run: ./tbc-video-export.AppImage --version

      - name: Upload AppImage to GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}

        run: >-
          gh release upload
          '${{ github.ref_name }}' 'tbc-video-export.AppImage#tbc-video-export-${{ github.ref_name }}.AppImage'
          --repo '${{ github.repository }}'
