---
name: Build
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-dists:
    name: Build dists
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          fetch-depth: 1
          fetch-tags: false
          persist-credentials: false

      - name: Install Nix
        uses: NixOS/nix-installer-action@6b8548fe06acfb0155a50ab5d561accb215764cc  # zizmor: ignore[ref-version-mismatch]
        with:
          extra-conf: |
            experimental-features = flakes nix-command
            accept-flake-config = true
            auto-optimise-store = false # https://github.com/nix-community/cache-nix-action/issues/170

      - name: Restore/save Nix cache
        uses: nix-community/cache-nix-action@7df957e333c1e5da7721f60227dbba6d06080569  # v7.0.2
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock', '**/uv.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          purge: true
          purge-prefixes: nix-${{ runner.os }}-
          purge-created: PT10S
          purge-primary-key: never

      - name: Build
        run: nix build .#dist

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: python-package-distributions
          path: result/
          if-no-files-found: error

  build-windows:
    name: Build Windows binary
    runs-on: windows-latest

    permissions:
      actions: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: false

      - name: Install python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1  # v6.3.0
        with:
          python-version: "3.14"

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39  # v8.2.0

      - name: Build
        run: uv run --script .\scripts\build_windows.py

      - name: Test binary
        run: .\dist\tbc-video-export.exe --version

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: windows-binary
          path: .\dist\tbc-video-export.exe
          if-no-files-found: error
