name: "Build"

on:
  workflow_run:
    workflows: [Tests]

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: cachix/install-nix-action@v23

      - name: Install
        run: nix develop --impure --accept-flake-config --command poetry install

      - name: Build
        run: nix develop --impure --accept-flake-config --command poetry build

      - name: Store the distribution packages
        uses: actions/upload-artifact@v3
        with:
          name: python-package-distributions
          path: dist/
