name: "Build and Release PyInstaller Binaries"

on:
  workflow_run:
    #workflows: [Tests, PyPI]
    workflows: [Tests]

jobs:
  pyinstaller-win:
    name: pyinstaller-win
    runs-on: windows-latest

    #if: |
    #  ${{ github.event.workflow_run.conclusion == 'success' }} &&
    #  if: startsWith(github.ref, 'refs/tags/v')
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Setup Environment
        run: |
          python -m venv .venv
          New-Item -ItemType Directory -Path .\build
          .\venv\Scripts\Activate.ps1
          pip install poetry

      - name: Setup dependencies
        run: poetry install --with=pyinstaller

      - name: Create PyInstaller binary
        run: poetry run pyinstaller/build_windows.py

      - name: Test
        run: Get-ChildItem .\dist\

      #- name: Upload binary to GitHub Release
      #  env:
      #    GITHUB_TOKEN: ${{ github.token }}
#
#  run: >-
#    gh release upload
#    '${{ github.ref_name }}' '.\dist\tbc-video-export.exe#tbc-video-export-${{ github.ref_name }}.exe'
#    --repo '${{ github.repository }}'
