name: "Tests"

on:
  pull_request:
  workflow_call:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: cachix/install-nix-action@v25

      - name: Install
        run: nix develop --impure --accept-flake-config --command poetry install

      - name: Create fake binaries to satisfy tests (fixme)
        run: touch ffmpeg ld-dropout-correct ld-chroma-decoder ld-process-vbi ld-process-efm ld-export-metadata

      - name: Run unit tests
        run: nix develop --impure --accept-flake-config --command poetry run python -m unittest
